name: rdf
description: A library for working with RDF data written in native Dart.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  petitparser: ^4.4.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  petitparser: ^4.4.0
